### ISSUE TITLE
Error on "Installing Pods" step

### ISSUE THREAD

**Issue by twof** [bow-swift/nef#105]
```
→ nef playground --platform osx
Installing Playground (BowPlayground)... ✅
Set BowPlayground target to macOS ✅
Updating version (0.7.0)... ✅
Installing Pods ... ❌
error: pod install review 'nef/log/pod-install.log' for more information.
```

`nef/log/pod-install.log` doesn't exist in the current directory so there's no way for me to check logs.

**Comment by miguelangel-dev** [comment]
Ey @twof, thanks so much to give nef a try!

Firstly, upgrade nef to v0.5.1
```
brew upgrade nef
```

It is happening, because we have a dependency to a future `bow` version - `Bow 0.7.0` but is is not ready in `cocoapods` - thanks for alert us about it! - I have added a section of `known issues` in the [Readme](https://github.com/bow-swift/nef/blob/master/README.md#known-issues)

While we are working on the release for the next Bow version, you can run
```bash
→ nef playground --platform osx --bow-version 0.6.0
```

On another hand, when you run `nef playground` it will create a nef Xcode Playground package. If you run `ls -la` you will alert it is an app with Playground appearance! So, you can open it with `right button of your mouse > Show Package Contents` - inside it, you will find the `nef` folder. In this folder, nef will be writing everything related to installation (derived data, frameworks...), logs, ...

In this case, also you can check the log running:
```bash
→ cat BowPlayground.app/nef/log/pod-install.log
```

![Screenshot 2019-12-12 at 11 22 53](https://user-images.githubusercontent.com/25568562/70704271-f907c500-1cd1-11ea-9e9a-7fdabd322f43.png)
![Screenshot 2019-12-12 at 11 23 07](https://user-images.githubusercontent.com/25568562/70704272-f907c500-1cd1-11ea-8354-0667f96a8dec.png)

Related to your comment, and to help the log review in external systems, for example, CI.  I have created this [issue](https://github.com/bow-swift/nef/issues/106).

Just to clarify, using `--platform` you will create an Xcode Playground compatible with `macOS` system (you can import fw like AppKit) and using iOS (default: to use frameworks for iOS system, UIKit...). 
If you want to create a Playground compatible with iPad, from yesterday (nef v0.5), you can run `nef ipad` or using the [Xcode Extension](https://github.com/bow-swift/nef-plugin) - [installer](https://github.com/bow-swift/nef-plugin/releases/download/2.0.0/nef-installer-v2_0_0.dmg)

Please keep us updated about your progress !! 🎉

**Comment by twof** [comment]
@miguelangel-dev Thanks! It looks like it's working now.
